services:

#Repository
    atrapalo.infrastructure.persistence.doctrine.doctrine_entity_repository:
        class: Atrapalo\Infrastructure\Persistence\Doctrine\DoctrineEntityRepository
        abstract: true
        arguments:
            - "@doctrine.orm.entity_manager"

    atrapalo.infrastructure.model.album.repository.album_repository:
        class: Atrapalo\Infrastructure\Model\Album\Repository\AlbumRepositoryImpl
        parent: "atrapalo.infrastructure.persistence.doctrine.doctrine_entity_repository"

    atrapalo.infrastructure.model.genre.repository.genre_repository:
        class: Atrapalo\Infrastructure\Model\Genre\Repository\GenreRepositoryImpl
        parent: "atrapalo.infrastructure.persistence.doctrine.doctrine_entity_repository"

    atrapalo.infrastructure.model.media_type.repository.media_type_repository:
        class: Atrapalo\Infrastructure\Model\MediaType\Repository\MediaTypeRepositoryImpl
        parent: "atrapalo.infrastructure.persistence.doctrine.doctrine_entity_repository"

    atrapalo.infrastructure.model.track.repository.track_repository:
        class: Atrapalo\Infrastructure\Model\Track\Repository\TrackRepositoryImpl
        parent: "atrapalo.infrastructure.persistence.doctrine.doctrine_entity_repository"
        arguments:
            - "@ruflin.elastica.search"
            
    atrapalo.infrastructure.model.playlist.repository.playlist_repository:
        class: Atrapalo\Infrastructure\Model\PlayList\Repository\PlayListRepositoryImpl
        parent: "atrapalo.infrastructure.persistence.doctrine.doctrine_entity_repository"
        arguments:
            - "@ruflin.elastica.search"



#DataTransformer
    atrapalo.infrastructure.model.track.data_transformer.track_to_track_resource_data_transformer:
        class: Atrapalo\Infrastructure\Model\Track\DataTransformer\TrackToTrackResourceDataTransformer
        arguments:
            - @atrapalo.infrastructure.model.album.data_transformer.album_to_album_resource_data_transformer
            - @atrapalo.infrastructure.model.media_type.data_transformer.media_type_to_media_type_resource_data_transformer
            - @atrapalo.infrastructure.model.genre.data_transformer.genre_to_genre_resource_data_transformer

    atrapalo.infrastructure.model.album.data_transformer.album_to_album_resource_data_transformer:
        class: Atrapalo\Infrastructure\Model\Album\DataTransformer\AlbumToAlbumResourceDataTransformer

    atrapalo.infrastructure.model.media_type.data_transformer.media_type_to_media_type_resource_data_transformer:
        class: Atrapalo\Infrastructure\Model\MediaType\DataTransformer\MediaTypeToMediaTypeResourceDataTransformer

    atrapalo.infrastructure.model.genre.data_transformer.genre_to_genre_resource_data_transformer:
        class: Atrapalo\Infrastructure\Model\Genre\DataTransformer\GenreToGenreResourceDataTransformer

    atrapalo.infrastructure.model.playlist.data_transformer.playlist_to_playlist_resource_data_transformer:
        class: Atrapalo\Infrastructure\Model\PlayList\DataTransformer\PlayListToPlayListResourceDataTransformer



#CommandHandler DataTransformer
    atrapalo.infrastructure.model.track.command_handler.get_track.data_transformer.get_track_command_result_to_track_resource_data_transformer:
        class: Atrapalo\Infrastructure\Model\Track\CommandHandler\GetTrack\DataTransformer\GetTrackCommandResultToTrackResourceDataTransformer
        arguments: [@atrapalo.infrastructure.model.track.data_transformer.track_to_track_resource_data_transformer]

    atrapalo.infrastructure.model.playlist.command_handler.search_playlists.data_transformer.search_playlists_command_result_to_playlist_resource_array_data_transformer:
        class: Atrapalo\Infrastructure\Model\PlayList\CommandHandler\SearchPlayLists\DataTransformer\SearchPlayListsCommandResultToPlayListResourceArrayDataTransformer
        arguments: [@atrapalo.infrastructure.model.playlist.data_transformer.playlist_to_playlist_resource_data_transformer]

    atrapalo.infrastructure.model.track.command_handler.search_tracks.data_transformer.search_tracks_command_result_to_track_resource_array_data_transformer:
        class: Atrapalo\Infrastructure\Model\Track\CommandHandler\SearchTracks\DataTransformer\SearchTracksCommandResultToTrackResourceArrayDataTransformer
        arguments: [@atrapalo.infrastructure.model.track.data_transformer.track_to_track_resource_data_transformer]

    atrapalo.infrastructure.model.track.command_handler.create_track.data_transformer.create_track_command_result_to_track_resource_data_transformer:
        class: Atrapalo\Infrastructure\Model\Track\CommandHandler\CreateTrack\DataTransformer\CreateTrackCommandResultToTrackResourceDataTransformer
        arguments: [@atrapalo.infrastructure.model.track.data_transformer.track_to_track_resource_data_transformer]



#CommandHandler
    atrapalo.application.model.track.create_track.create_track_command_handler:
        class: Atrapalo\Application\Model\Track\CreateTrack\CreateTrackCommandHandler
        arguments:
            - @atrapalo.infrastructure.model.track.command_handler.create_track.data_transformer.create_track_command_result_to_track_resource_data_transformer
            - @atrapalo.infrastructure.model.album.repository.album_repository
            - @atrapalo.infrastructure.model.genre.repository.genre_repository
            - @atrapalo.infrastructure.model.media_type.repository.media_type_repository
            - @atrapalo.infrastructure.model.playlist.repository.playlist_repository
            - @atrapalo.infrastructure.model.track.repository.track_repository

    atrapalo.application.model.track.get_track.get_track_command_handler:
        class: Atrapalo\Application\Model\Track\GetTrack\GetTrackCommandHandler
        arguments:
            - @atrapalo.infrastructure.model.track.command_handler.get_track.data_transformer.get_track_command_result_to_track_resource_data_transformer
            - @atrapalo.infrastructure.model.track.repository.track_repository

    atrapalo.application.model.playlist.search_playlists.search_playlists_command_handler:
        class: Atrapalo\Application\Model\PlayList\CommandHandler\SearchPlaylists\SearchPlayListsCommandHandler
        arguments:
            - @atrapalo.infrastructure.model.playlist.command_handler.search_playlists.data_transformer.search_playlists_command_result_to_playlist_resource_array_data_transformer
            - @atrapalo.infrastructure.model.playlist.repository.playlist_repository

    atrapalo.application.model.track.search_tracks.search_tracks_command_handler:
        class: Atrapalo\Application\Model\Track\SearchTracks\SearchTracksCommandHandler
        arguments:
            - @atrapalo.infrastructure.model.track.command_handler.search_tracks.data_transformer.search_tracks_command_result_to_track_resource_array_data_transformer
            - @atrapalo.infrastructure.model.track.repository.track_repository



#Elastica
    ruflin.elastica.client:
        class: Elastica\Client

    ruflin.elastica.search:
        class: Elastica\Search
        arguments: [@ruflin.elastica.client]

    cocur.slugify:
        class: Cocur\Slugify\Slugify